#!/usr/bin/env python
import thread, os

if __name__ == "__main__":
  from vaporos_vaportransport import GUI, Server
  # Setup the FTP server and gui
  port = 2020
  server = Server(port)
  gui = GUI(server)

  # Run the server
  try:
   thread.start_new_thread(server.run, ())
  except:
    print("Error: unable to start server thread")

  # Run the GUI
  gui.run()
